FROM python:3.8-alpine

COPY . /urs/fastApiProject

WORKDIR /urs/fastApiProject

RUN pip install fastapi uvicorn pydantic

CMD ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]

