FROM python:3.11-alpine

COPY . /usr/fastApiProjectRobotTests/

WORKDIR /usr/fastApiProjectRobotTests

RUN pip install robotframework requests robotframework-requests robotframework-jsonlibrary

