FROM python:3.11-alpine

COPY . /usr/fastApiProjectRobotTests/tests

WORKDIR /usr/fastApiProjectRobotTests/tests

RUN pip install robotframework requests robotframework-requests robotframework-jsonlibrary

